{{- $top := . -}}
{{- $values := .Values -}}
{{- if .Values.web.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.name" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 2 }}
  {{- if .Values.argoRollouts.enabled }}
  replicas: 0
  {{- else if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.web.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web.selector.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" . | nindent 8 }}
      annotations:
        {{- $valsweb := .Values.web -}}
        {{- $bothweb := merge $valsweb (pick .Values "linkerd") }}
        {{- include "calculate.pod.annotations" $bothweb | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "service.account.name" . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.web.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.externalSecret.enabled .Values.web.additionalVolumes }}
      volumes:
        {{- if .Values.externalSecret.enabled }}
        - name: secret-volume
          secret:
            secretName: {{ include "secret.name" . }}
        {{- end }}
        {{- with .Values.web.additionalVolumes }}
        {{- tpl . $top | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "container.name" . }}
          image: "{{ required ".Values.image.repository must be set" .Values.image.repository }}:{{ include "appVersion" . }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if or .Values.externalSecret.enabled .Values.web.additionalVolumeMounts }}
          volumeMounts:
            {{- if .Values.externalSecret.enabled }}
            {{- include "externalsecret.volumemount" . | nindent 12 }}
            {{- end }}
            {{- with .Values.web.additionalVolumeMounts }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            {{- if .Values.web.ports }}
            {{- toYaml .Values.web.ports | nindent 12 }}
            {{- else }}
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- end }}
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "container.env" .Values.web | indent 12 -}}
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          {{- if .Values.configmap.data }}
          envFrom:
            - configMapRef:
                name: {{ include "name" . }}
            {{- with .Values.web.additionalEnvFrom }}
            {{- tpl . $top | nindent 12 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- with .Values.web.command }}
          command:
            {{- range . }}
            - {{ . | quote  }}
            {{- end }}
          {{- end }}
          {{- with .Values.web.args }}
          args:
            {{- range . }}
            - {{ . | quote  }}
            {{- end }}
          {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}