# Default values for identity-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide the amount of pods if HPA is not enabled
##
replicaCount: 2

## Provide the image docker tag default: latest
##
appVersion: latest

## Manage docker image properties
##
image:
  ## Provide docker repository hub
  ##
  repository: frontegg/hybrid-identity-service
  ## Provide image pull policy
  ##
  pullPolicy: Always

## Provide secret name for frontegg's repository
##
imagePullSecrets:
  - name: regcred

## Provide a name in place of identity-service for `app:` labels
##
nameOverride: ""
## Provide a name in place of {releaseName}-identity-service
##
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
# fsGroup: 2000

## Setup Service properties for identity-service (open only one port)
##
service:
  ## Set service type
  ##
  type: ClusterIP
  ## Set service port
  ##
  protocol: TCP
  ## Set service target port to map
  ##
  port: 80
  ## Set port protocol default: TCP
  ##
  targetPort: 3016
  ## Set port name
  ##
  name: access-port

## HPA properties for identity-service
## If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
## If autoscaling is disabled identity-service will be managed by replicaset with `replicaCount` determine pod amount
##
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 75

## Set identity-service resources
##
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 250m
    memory: 512Mi


nodeSelector:
  "beta.kubernetes.io/os": linux

## Provide deployment tolerations
##
tolerations: []

## Provide deployment affinity
##
affinity: {}

configuration:
  secrets: {}
  map: {}

## Set database connection string values
##
database:
  host: ""
  username: ""
  password: ""
  ssl: "true"
  name: "frontegg_identity"
## Set Redis connection string values
##
redis:
  host: ""
  password: ""
  port: "6379"
  tls: "true"

## Set Kafka properties
##
kafka:
  enabled: false
  brokerList: ""
  password: ""
  username: ""
  topicName: AUDIT_TRIGGERED

## Frontegg's services url for inner communications
## Provide an alternate url for a service if a service name was changed
##
network:
  teamServiceUrl: http://frontegg-team-management-service

## Set frontegg's api key for emails
##
email:
  apiKey: ""

## Set Frontegg's api key for emails
##
frontegg:
  ## Set Frontegg provided in frontegg's portal administration
  ##
  clientId: ""
  apiKey: ""
  ## Set Frontegg's Authentication Url
  ##
  authenticationUrl: "https://api.frontegg.com/vendors/auth/token"
  ## Set Frontegg's identity service url
  ##
  managedIdentityServiceUrl: "https://api.frontegg.com/identity"
  ## override email template redirection url
  ##
  emailTemplateRedirectUrl: ""
  sync:
    ## Enable Configuration sync process with Frontegg's managed cloud
    ##
    enabled: "true"
    ## Set authentication failure retry delay in milliseconds.
    ##
    authenticationRetryDelay: "5000"
    ## Set sync time interval (minutes) with Frontegg's managed cloud.
    ##
    intervalTime: "15"
    ## Set true to shutdown secure access in case of authentication failure on pod startup.
    ##
    shutdownOnAuthenticationFailure: "true"
