apiVersion: v2
name: team-management-service
description: Frontegg Team Management Service Helm chart for Kubernetes
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.40
icon: https://frontegg.com/wp-content/uploads/2020/04/logo_frontegg.svg
maintainers:
  - name: "Guy Ludvig"
    email: "guy@frontegg.com"
