{{- $values := .Values -}}
{{- $top := . -}}
{{- range $jobName, $job := $values.jobs -}}
{{- if $job.enabled }}
{{- $defaultSyncWave := true -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "unified.name" $top | replace "-" "" | trunc 15 }}{{ $jobName | trunc 7 }}{{ $values.appVersion }}
  labels:
    {{- include "unified.jobLabels" $top | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
  annotations:
    {{- if $job.metadata }}
    {{- with $job.metadata.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- if (index . "argocd.argoproj.io/sync-wave") }}
    {{- $defaultSyncWave = false }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if $defaultSyncWave }}
    # default sync wave for jobs
    argocd.argoproj.io/sync-wave: "-501"
    {{- end }}
spec:
  {{- with $job.spec }}
  completions: {{ .completions | default 1 }}
  parallelism: {{ .parallelism | default 1 }}
  backoffLimit: {{ .backoffLimit | default 1 }}
  template:
    metadata:
      name: {{ include "unified.name" $top }}-{{ $jobName }}-{{ $values.appVersion }}
      labels:
        {{- include "unified.jobLabels" $top | nindent 8 }}
        app.kubernetes.io/component: {{ $jobName }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .restartPolicy | default "Never" }}
      {{- with $values.imagePullSecrets }}
      imagePullSecrets :
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $values.externalSecret.enabled }}
      volumes:
        - name: vol-secret
          secret:
            secretName: {{ include "external-secret-unique-name" $ }}
      {{- end }}
      containers:
        - name: {{ include "unified.name" $top }}-{{ $jobName }}
          image: "{{ $values.image.repository }}:{{ $values.appVersion }}"
          imagePullPolicy: {{ $values.imagePullPolicy }}
          {{- if $values.externalSecret.enabled }}
          volumeMounts:
            {{- include "unified.externalsecret.volumemount" $ | nindent 12 }}
          {{- end }}
          env:
            {{- include "unified.container.env" . | nindent 12 }}
            {{- if $values.externalSecret.enabled }}
            - name: FRONTEGG_CONFIG_DIRECTORY
              value: "/etc/config"
            {{- end }}
            {{- range $config_name, $localValues := $values.configuration.map }}
            {{- range $key, $value :=  $localValues }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "unified.name" $top }}-configmap
          command:
            {{- range .command }}
            - {{ . | quote  }}
            {{- end }}
          args:
            {{- range .args }}
            - {{ . | quote  }}
            {{- end }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- if $values.nodeSelector }}
      nodeSelector:
      {{- toYaml $values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $values.tolerations }}
      tolerations:
      {{- toYaml $values.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
