version: '3.8'

services:
  api-gateway:
    image: frontegg/hybrid-api-gateway:${API_GATEWAY_TAG}
    container_name: frontegg-api-gateway
    ports:
      - 9090:9090
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_HYBRID_MODE=true
      - FRONTEGG_AUTH_PUBLIC_KEY=
      - FRONTEGG_HYBRID_SERVICES=webhook,event,integrations

  connectors-worker:
    image: frontegg/hybrid-connectors-worker:${CONNECTOR_WORKERS_TAG}
    container_name: frontegg-connectors-worker
    ports:
      - 3015
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_KAFKA_SLACK_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_SLACK_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_KAFKA_EMAIL_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_EMAIL_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_KAFKA_SMS_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_SMS_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_KAFKA_EVENTS_STATUS_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_EVENTS_STATUS_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_HOST=${REDIS_HOST}
      - FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PORT=${REDIS_PORT}
      - FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_DB_INDEX=7
      - FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_TLS=${REDIS_TLS}
      - FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PASSWORD=${REDIS_PASSWORD}
      - FRONTEGG_CHANNELS_TO_RUN=
      - FRONTEGG_TWILIO_SENDER=
      - FRONTEGG_TWILIO_TOKEN=
      - FRONTEGG_TWILIO_ACCOUNTSID=
      - FRONTEGG_EMAIL_PROVIDER=
      - FRONTEGG_AWS_ACCESS_KEY_ID=
      - FRONTEGG_AWS_SECRET_ACCESS_KEY=
      - FRONTEGG_AWS_REGION=
      - FRONTEGG_SENDGRID_API_KEY=

  event-service:
    image: frontegg/hybrid-event-service:${EVENT_SERVICE_TAG}
    container_name: frontegg-event-service
    ports:
      - 3011
    env_file:
      - ./.common.env
    networks:
      - frontegg-network
    environment:
      - FRONTEGG_EVENT_MYSQL_DB_NAME=frontegg_events
      - FRONTEGG_EVENTS_MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - FRONTEGG_EVENTS_MYSQL_DB_USERNAME=${MYSQL_DB_USERNAME}
      - FRONTEGG_EVENTS_MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - FRONTEGG_TRIGGER_SLACK_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_SLACK_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_WEBHOOK_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_WEBHOOK_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_WEBPUSH_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_WEBPUSH_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_AUDIT_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_AUDIT_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_BELL_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_BELL_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_SMS_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_SMS_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_TRIGGER_EMAIL_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_TRIGGER_EMAIL_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_EVENTS_SERVICE_EVENTS_STATUSES_CONSUMER_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_EVENTS_SERVICE_EVENTS_CONSUMER_TOPIC=event-triggered-v1
      - FRONTEGG_EVENTS_SERVICE_EVENTS_STATUSES_CONSUMER_TOPIC=UPDATE_EVENT_STATUS
      - FRONTEGG_EVENTS_SERVICE_EVENTS_CONSUMER_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_EVENTS_SERVICE_EVENTS_CONSUMER_SASL_USERNAME=${KAFKA_SASL_USERNAME}
      - FRONTEGG_EVENTS_SERVICE_EVENTS_CONSUMER_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_EVENTS_SERVICE_REDIS_HOST=${REDIS_HOST}
      - FRONTEGG_EVENTS_SERVICE_REDIS_PORT=${REDIS_PORT}
      - FRONTEGG_EVENTS_SERVICE_REDIS_PASSWORD=${REDIS_PASSWORD}
      - FRONTEGG_EVENTS_SERVICE_REDIS_DB_INDEX=7
      - FRONTEGG_EVENTS_SERVICE_REDIS_TLS=${REDIS_TLS}
      - FRONTEGG_EVENT_SERVICE_HYBRID_SYNC_ENABLED=true
      - FRONTEGG_EVENT_SERVICE_HYBRID_SYNC_INTERVAL_MINUTES=15
      - FRONTEGG_CLIENT_ID=
      - FRONTEGG_API_KEY=
      - FRONTEGG_EVENT_SERVICE_HYBRID_AUTH_RETRY_DELAY_MS=5000
      - FRONTEGG_EVENT_SERVICE_HYBRID_SHUTDOWN_ON_INITIAL_AUTH_FAILURE=true

  integrations-service:
    image: frontegg/hybrid-integrations-service:${INTEGRATIONS_SERVICE_TAG}
    container_name: frontegg-integration-service
    ports:
      - 3014
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_INTEGRATIONS_SERVICE_MONGODB_URL=
      - FRONTEGG_INTEGRATIONS_SERVICE_SLACK_ENCRYPTION_SECRET=
      - FRONTEGG_INTEGRATION_SERVICE_SLACK_CONFIG_UPDATE_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_INTEGRATION_SERVICE_SLACK_CONFIG_UPDATE_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_INTEGRATION_SERVICE_EMAIL_CONFIG_UPDATE_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_INTEGRATION_SERVICE_EMAIL_CONFIG_UPDATE_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_INTEGRATION_SERVICE_SMS_CONFIG_UPDATE_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_INTEGRATION_SERVICE_SMS_CONFIG_UPDATE_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}

  webhook-service:
    image: frontegg/hybrid-webhook-service:${WEBHOOK_SERVICE_TAG}
    container_name: frontegg-webhook-service
    ports:
      - 3013
    networks:
      - frontegg-network
    env_file:
      - ./.common.env
    environment:
      - FRONTEGG_WEBHOOK_SERVICE_MONGODB_URL=
      - FRONTEGG_WEBHOOK_SERVICE_MONGODB_CONNECTION_RETRY_ATTEMPTS=3
      - FRONTEGG_WEBHOOK_SERVICE_MONGODB_CONNECTION_RETRY_DELAY=1000
      - FRONTEGG_KAFKA_BROKER_LIST=${KAFKA_BROKER_LIST}
      - FRONTEGG_KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - FRONTEGG_EVENTS_PUBSUB_TOPIC=events
      - FRONTEGG_WEBHOOK_MYSQL_DB_NAME=frontegg_webhooks
      - FRONTEGG_WEBHOOK_MYSQL_DB_HOST=${MYSQL_DB_HOST}
      - FRONTEGG_WEBHOOK_MYSQL_DB_USERNAME=${MYSQL_DB_USERNAME}
      - FRONTEGG_WEBHOOK_MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}

networks:
  frontegg-network:
    driver: bridge
