{{- $top := . }}
{{- with .Values.web.serviceProfile }}
{{- if .enabled }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: {{ include "web.name" $top }}.frontegg.svc.cluster.local
  namespace: {{ .namespace | default "frontegg" }}
spec:
  routes:
    {{- .routes | toYaml | nindent 4 }}
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: frontegg-{{ include "web.name" $top }}.frontegg.svc.cluster.local
  namespace: {{ .namespace | default "frontegg" }}
spec:
  routes:
    {{- . | toYaml | nindent 4 }}
{{- end }}
{{- end }}