{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "api-gateway.fullname" . }}
{{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
{{- end }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
    {{- if .Values.prometheusRule.labels }}
    {{- toYaml .Values.prometheusRule.labels | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.prometheusRule.rules }}
  groups:
    - name: frontegg.{{ include "api-gateway.name" . }}.rules
      rules: {{ tpl (toYaml .Values.prometheusRule.rules) . | nindent 8 }}
{{- end }}
{{- end }}
