{{- if .Values.highPriority.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unified.name" . }}-deployment-hp
  labels:
  {{- include "unified.hp.labels" . | nindent 4 }}
  {{- toYaml .Values.highPriority.labels | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  {{- if .Values.argoRollouts }}
  replicas: 0
  {{- else if not .Values.web.autoscaling.enabled }}
  replicas: {{ .Values.highPriority.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "unified.hp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "unified.hp.labels" . | nindent 8 }}
        {{- with .Values.podLabels  }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
        {{- with .Values.web.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.highPriority.serviceAccountName }}
      serviceAccountName: {{ tpl . $ }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.highPriority.terminationGracePeriodSeconds | default 30 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.externalSecret.enabled }}
      volumes :
        - name : vol-secret
          secret :
            secretName : {{ include "external-secret-unique-name" . }}
      {{- end }}
      containers:
        - name: {{ include "unified.name" . }}-hp
          image: "{{ required ".Values.image.repository must be set" .Values.image.repository }}:{{ include "appVersion" . }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.externalSecret.enabled }}
          volumeMounts :
            {{- include "unified.externalsecret.volumemount" . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }} # change this to 80 in the future
              protocol: TCP
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "unified.container.env" .Values.highPriority | nindent 12 }}
            {{- if .Values.externalSecret.enabled }}
            - name: FRONTEGG_CONFIG_DIRECTORY
              value: "/etc/config"
            {{- end }}
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "unified.name" . }}-configmap
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          command:
            {{- range .Values.web.command }}
            - {{ . | quote  }}
            {{- end }}
          args:
            {{- range .Values.web.args }}
            - {{ . | quote  }}
            {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
