apiVersion: v2
name: audits-service
description: Frontegg Audits Service Helm chart
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.31

maintainers:
  - name: "Guy Ludvig"
    email: "guy@frontegg.com"
